---
title: "lab3_analisis_de_datos"
output: html_document
date: "2024-06-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(mice)
library(tidyr)
library(arules)
library(arulesViz)
```

## 

```{r lectura}
FILENAME = 'data.csv'
dataset = read.csv(FILENAME, row.names = 1, colClasses = "integer")
cols = colnames(dataset)
na_count = summarise_all(dataset, ~sum(is.na(.)))

str(dataset)
print(dataset)
print(na_count)
```
```{r imputar_schooling}
# Hacer una copia del dataset original
cleaned_dataset = dataset

# Imputar la columna 'Schooling' usando la mediana
cleaned_dataset$Schooling = with(cleaned_dataset, ifelse(is.na(Schooling), median(Schooling, na.rm = TRUE), Schooling))

# Convertir 'Schooling' a entero
cleaned_dataset$Schooling = as.integer(cleaned_dataset$Schooling)

# Mostrar información del dataset
na_count = summarise_all(cleaned_dataset, ~sum(is.na(.)))

print(na_count)
str(cleaned_dataset)
```



```{r imputar_initial_symptom}
# Definir la función para calcular la moda (valor más frecuente)
calculate_mode = function(x) {
  freq = table(x)
  as.numeric(names(freq)[which.max(freq)])
}

# Imputar la columna 'Initial_Symptom' usando la moda
mode_value = calculate_mode(cleaned_dataset$Initial_Symptom[!is.na(cleaned_dataset$Initial_Symptom)])
cleaned_dataset$Initial_Symptom[is.na(cleaned_dataset$Initial_Symptom)] = mode_value

# Convertir 'Initial_Symptom' a entero
cleaned_dataset$Initial_Symptom = as.integer(cleaned_dataset$Initial_Symptom)

# Contar y mostrar la cantidad de valores nulos en cada columna
na_count = summarise_all(cleaned_dataset, ~sum(is.na(.)))

# Mostrar información de nulos y un resumen del dataset
print(na_count)
str(cleaned_dataset)
```



```{r limpiar_edss}
cleaned_dataset$Initial_EDSS = NULL
cleaned_dataset$Final_EDSS = NULL
str(cleaned_dataset)
```



## Categorizacion de variables numericas


# Variable Age

```{r categorizacion_age}
# Categorizar la variable 'age' según los rangos definidos
codified_dataset = cleaned_dataset
codified_dataset = codified_dataset %>%
  mutate(Age_Category = cut(Age,
                            breaks = c(-Inf, 20, 50, Inf),
                            labels = c("<20", "20-50", ">50"),
                            right = FALSE))
# Ver el resultado
str(codified_dataset)
# Mostrar la distribución de las categorías de edad
table(codified_dataset$Age_Category)
```

# Variable Schooling

```{r categorizacion_}

# Categorizar la variable 'Schooling' según los rangos de escolaridad en México
codified_dataset <- codified_dataset %>%
  mutate(Education_Level = cut(Schooling,
                               breaks = c(-Inf, 0, 6, 9, 12, 17, 25),
                               labels = c("Sin Educación Formal", "Educación Primaria", "Educación Secundaria", 
                                          "Educación Media Superior", "Educación Superior", "Posgrado"),
                               right = TRUE))

# Ver el resultado
str(codified_dataset)

# Mostrar distribución de las categorías de escolaridad
table(codified_dataset$Education_Level)
```

# Codificacion de variable Initial_Symptom

```{r categorizacion_}

codified_dataset$Initial_Symptom <- factor(codified_dataset$Initial_Symptom, levels = 1:15, 
  labels = c("Visual", "Sensorial", "Motor", "Otro", "Visual y Sensorial", "Visual y Motor", 
             "Visual y Otro", "Sensorial y Motor", "Sensorial y Otro", "Motor y Otro", 
             "Visual, Sensorial y Motor", "Visual, Sensorial y Otro", "Visual, Motor y Otro", 
             "Sensorial, Motor y Otro", "Visual, Sensorial, Motor y Otro"))

# Realizamos el one-hot encoding
codified_dataset <- codified_dataset %>%
  mutate(ID = row_number()) %>%
  separate_rows(Initial_Symptom, sep = ", ") %>%
  separate_rows(Initial_Symptom, sep = " y ") %>%
  mutate(value = TRUE) %>%
  pivot_wider(names_from = Initial_Symptom, values_from = value, values_fill = list(value = FALSE)) %>%
  select(-ID)

# Ver el resultado
str(codified_dataset)
```
```{r format}
codified_dataset$Age = NULL
codified_dataset$Schooling = NULL
codified_dataset
```


```{r set_factor}
factor_dataset = codified_dataset

# Diccionarios de mapeo
gender = c("1" = "Masculino", "2" = "Femenino")  # Suponiendo masculino como TRUE, femenino como FALSE
breastfeeding = c("1" = TRUE, "2" = FALSE, "3" = NA)  # NA para Desconocido
varicella = c("1" = TRUE, "2" = FALSE, "3" = NA) # NA para Desconocido
mono_or_polysymptomatic = c("1" = "Monosintomatico", "2" = "Polisintomatico", "3" = "Desconocido")
oligoclonal_bands = c("0" = FALSE, "1" = TRUE, "2" = NA) # NA para Desconocido
neg_pos = c("0" = FALSE, "1" = TRUE)
group = c("1" = TRUE, "2" = FALSE)  # EMCD como TRUE, No EMCD como FALSE
neg_pos_vars = c("LLSSEP", "ULSSEP", "VEP", "BAEP", "Periventricular_MRI",
                "Cortical_MRI", "Infratentorial_MRI", "Spinal_Cord_MRI")

# Aplicación de mapeos
factor_dataset$Gender = factor(factor_dataset$Gender, levels = names(gender), labels = gender)
factor_dataset$Breastfeeding = as.logical(factor(factor_dataset$Breastfeeding, levels = names(breastfeeding), labels = breastfeeding))
factor_dataset$Varicella = as.logical(factor(factor_dataset$Varicella, levels = names(varicella), labels = varicella))
factor_dataset$Mono_or_Polysymptomatic = factor(factor_dataset$Mono_or_Polysymptomatic, levels = names(mono_or_polysymptomatic), labels = mono_or_polysymptomatic)
factor_dataset$Oligoclonal_Bands = as.logical(factor(factor_dataset$Oligoclonal_Bands, levels = names(oligoclonal_bands), labels = oligoclonal_bands))
factor_dataset$group = as.logical(factor(factor_dataset$group, levels = names(group), labels = group))

for (var in neg_pos_vars) {
  factor_dataset[[var]] = as.logical(factor(factor_dataset[[var]], levels = names(neg_pos), labels = neg_pos))
}

factor_dataset["EMCD"] = factor_dataset$group
factor_dataset["No_EMCD"] = !factor_dataset["EMCD"]

factor_dataset$Breastfeeding = NULL # Revisar
factor_dataset$group = NULL


# Llenar datos faltantes Monosintomatico
factor_dataset$num_sintomas = rowSums(factor_dataset[, c("Sensorial", "Motor", "Otro", "Visual")], na.rm = TRUE)
factor_dataset$Mono_or_Polysymptomatic[factor_dataset$Mono_or_Polysymptomatic == "Desconocido"] = ifelse(
  factor_dataset$num_sintomas[factor_dataset$Mono_or_Polysymptomatic == "Desconocido"] > 1,
  "Polisintomatico",  # Más de un síntoma inicial
  "Monosintomatico"   # Un único síntoma inicial
)
factor_dataset$num_sintomas = NULL

# Llenar datos faltantes varicella y Oligoconal_Bands
imputed_data = suppressWarnings(mice(factor_dataset, method = "pmm", m = 5, seed = 500,  printFlag = FALSE))
completed_data = complete(imputed_data)


na_count = summarise_all(completed_data, ~sum(is.na(.)))
print(na_count)
completed_data
```


# Generacion de reglas de asociacion

## EMCD como consecuente

```{r reglas_asociacion}

transacciones = as(completed_data, "transactions")

# Generar reglas de asociación con 'EMCD' como consecuente
reglas = apriori(transacciones, 
                 parameter = list(supp = 0.1, conf = 0.9, minlen = 2), 
                 appearance = list(default = "lhs", rhs = c("EMCD")),
                 control = list(verbose = TRUE))
reglas_filtradas = sort(reglas, by = "lift", decreasing = TRUE)
reglas_filtradas
top_10_reglas <- head(reglas_filtradas, n = 10)
# Visualizar reglas con un plot de dispersión
#plot(reglas_filtradas, method = "grouped")

# O visualizar como un grafo
#plot(top_10_reglas, method = "graph")
inspect(top_10_reglas)
```

## No EMCD como consecuente

```{r reglas_asociacion}

transacciones = as(completed_data, "transactions")

reglas = apriori(transacciones, 
                 parameter = list(supp = 0.06, conf = 0.75, minlen = 2), 
                 appearance = list(default = "lhs", rhs = c("No_EMCD")),
                 control = list(verbose = TRUE))
reglas_filtradas = sort(reglas, by = "lift", decreasing = TRUE)
reglas_filtradas
top_10_reglas <- head(reglas_filtradas, n = 10)
# Visualizar reglas con un plot de dispersión
#plot(reglas_filtradas, method = "grouped")

# O visualizar como un grafo
#plot(top_10_reglas, method = "graph")
inspect(top_10_reglas)
```

